channels:
  - conda-forge
  - nodefaults


dependencies:
  - pip
  - python>=3.8
  - h5py
  - sphinx
  - nbsphinx
  - numpydoc
  - sphinx_rtd_theme
  - ipython
  - pip:
    - sphinx_click
    - numpy
    - scipy
    - matplotlib
    - cached_property
    - astropy
    - edges-io
    - edges-cal
    - healpy
    - h5py
    - rich>=9.0
    - requests
    - tqdm
    - methodtools
    - tqdm
    - rich
    - attrs
    - questionary
    - pathos
